### ISSUE TITLE
bin-wrapper vulnerability

### ISSUE THREAD

**Issue by shiftgeist** [fenneclab/hugo-bin#106]
Hugo-bin is using `bin-wrapper` that is sub dependent on vulnerable version of `decompress`.
https://npmjs.com/advisories/1217

**Comment by XhmikosR** [comment]
This is an upstream issue and it's already reported without any fixes available

**Comment by XhmikosR** [comment]
See https://github.com/fenneclab/hugo-bin/issues/114#issuecomment-1469496820
