### ISSUE TITLE
Support for downloading binaries from mirror

### ISSUE THREAD

**Issue by bingenito** [fenneclab/hugo-bin#112]
Current postinstall binary download requires external access.  For many corporate environments we have an internal package repository.  It would be great if the root portion of the baseUrl can be overriden via env var much like pre-gyp downloads.  Are you open to this contribution?

https://github.com/fenneclab/hugo-bin/blob/e3e3030ce753f1091af0c2e60ffd193b7782c7d5/lib/index.js#L8

**Comment by XhmikosR** [comment]
You can submit a PR as long as there's a test for it.
