### ISSUE TITLE
[Question] Is there a way to check for Hugo Updates?

### ISSUE THREAD

**Issue by MartinHotmann** [fenneclab/hugo-bin#113]
I have this yarn dependencies installed:

"hugo-bin-extended": "^0.83.1"

And would like to check with this if a new version of Hugo (not "**`hugo-bin-extended`**") is available as I check with yarn if there are updates for any of my Node things.
I think it would be cool if **`hugo-bin`** and **`hugo-bin-extended`** could check for new Hugo versions and inform me that there is a new version for my used edition (**`hugo`**, or **`hugo-extended`**) available.
With this function I can check if there are updates available for Hugo with yarn or npm even if I can nopt update Hugo itself with **`hugo-bin`** or **`hugo-bin-extended`**.

For me this would be a good addition to the already given functionality and would help me having track of of there are updates available.

Thanks in advance!

**Comment by XhmikosR** [comment]
Nope, and I'd rather not include a dependency for this.

You can just use https://docs.npmjs.com/cli/v6/commands/npm-outdated or https://github.com/raineorshine/npm-check-updates
