### ISSUE TITLE
6 high severity vulnerabilities

### ISSUE THREAD

**Issue by h-enk** [fenneclab/hugo-bin#114]
0. mkdir hugo-bin && cd hugo-bin
1. npm init -y
2. npm install hugo-bin -D

```bash

added 184 packages, and audited 185 packages in 11s

8 packages are looking for funding
  run `npm fund` for details

6 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

```bash
# npm audit report

normalize-url  <=4.5.0 || 5.0.0 - 5.3.0 || 6.0.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1755
fix available via `npm audit fix --force`
Will install hugo-bin@0.30.0, which is a breaking change
node_modules/normalize-url
  cacheable-request  0.1.0 - 6.0.0
  Depends on vulnerable versions of normalize-url
  node_modules/cacheable-request
    got  8.0.0 - 9.5.0
    Depends on vulnerable versions of cacheable-request
    node_modules/got
      download  >=7.0.0
      Depends on vulnerable versions of got
      node_modules/download
        bin-wrapper  2.1.2 || >=4.0.0
        Depends on vulnerable versions of download
        node_modules/bin-wrapper
          hugo-bin  >=0.31.0
          Depends on vulnerable versions of bin-wrapper
          node_modules/hugo-bin

6 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
```

Regular Expression Denial of Service - https://npmjs.com/advisories/1755

Replace [`bin-wrapper`](https://github.com/kevva/bin-wrapper)?!

**Comment by XhmikosR** [comment]
There's only one vulnerability which cannot be fixed on our side https://github.com/kevva/download/issues/216

The rest can be fixed by running `npm audit fix` or regenerating paackage-lock.json.

**Comment by h-enk** [comment]
From the audit report: `Will install hugo-bin@0.30.0, which is a breaking change` — not what I want.

> The rest can be fixed by running npm audit fix or regenerating package-lock.json.

No, unfortunately not: running `npm audit fix [--force]` is only making things worse:

```bash
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating hugo-bin to 0.30.0,which is a SemVer major change.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 259 packages, removed 75 packages, changed 41 packages, and audited 369 packages in 13s

4 packages are looking for funding
  run `npm fund` for details

# npm audit report

braces  <2.3.1
Regular Expression Denial of Service - https://npmjs.com/advisories/786
fix available via `npm audit fix`
node_modules/braces
  micromatch  0.2.0 - 2.3.11
  Depends on vulnerable versions of braces
  Depends on vulnerable versions of parse-glob
  node_modules/micromatch
    glob-stream  >=5.3.0
    Depends on vulnerable versions of glob-parent
    Depends on vulnerable versions of micromatch
    node_modules/glob-stream
      vinyl-fs  >=2.4.2
      Depends on vulnerable versions of glob-stream
      node_modules/vinyl-fs

decompress  <4.2.1
Severity: high
Arbitrary File Write - https://npmjs.com/advisories/1217
fix available via `npm audit fix`
node_modules/decompress
  gulp-decompress  <=1.2.0
  Depends on vulnerable versions of decompress
  node_modules/gulp-decompress
    download  4.0.0 - 5.0.0
    Depends on vulnerable versions of caw
    Depends on vulnerable versions of gulp-decompress
    node_modules/download

glob-parent  <5.1.2
Severity: moderate
Regular expression denial of service - https://npmjs.com/advisories/1751
fix available via `npm audit fix`
node_modules/glob-base/node_modules/glob-parent
node_modules/glob-parent
  glob-base  *
  Depends on vulnerable versions of glob-parent
  node_modules/glob-base
    parse-glob  >=2.1.0
    Depends on vulnerable versions of glob-base
    node_modules/parse-glob
      micromatch  0.2.0 - 2.3.11
      Depends on vulnerable versions of braces
      Depends on vulnerable versions of parse-glob
      node_modules/micromatch
        glob-stream  >=5.3.0
        Depends on vulnerable versions of glob-parent
        Depends on vulnerable versions of micromatch
        node_modules/glob-stream
          vinyl-fs  >=2.4.2
          Depends on vulnerable versions of glob-stream
          node_modules/vinyl-fs

trim-newlines  <3.0.1 || =4.0.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1753
fix available via `npm audit fix --force`
Will install hugo-bin@0.72.1, which is a breaking change
node_modules/trim-newlines
  meow  3.4.0 - 5.0.0
  Depends on vulnerable versions of trim-newlines
  node_modules/meow
    del-cli  <=3.0.0
    Depends on vulnerable versions of meow
    node_modules/del-cli
      hugo-bin  0.3.1 || 0.4.1 || 0.5.1 || 0.6.1 - 0.30.0
      Depends on vulnerable versions of del-cli
      node_modules/hugo-bin
    find-versions  1.2.0 - 1.2.1
    Depends on vulnerable versions of meow
    node_modules/find-versions

tunnel-agent  <0.6.0
Severity: moderate
Memory Exposure - https://npmjs.com/advisories/598
fix available via `npm audit fix`
node_modules/tunnel-agent
  caw  <=2.0.0
  Depends on vulnerable versions of tunnel-agent
  node_modules/caw
    download  4.0.0 - 5.0.0
    Depends on vulnerable versions of caw
    Depends on vulnerable versions of gulp-decompress
    node_modules/download

17 vulnerabilities (1 low, 8 moderate, 8 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force
```

**Comment by XhmikosR** [comment]
I cannot reproduce. Like I said, there's only one vulnerability for me using Node.js 14.x/npm 6.x which is the current LTS.

**Comment by h-enk** [comment]
I think bin-wrapper@4.1.0 really is a problem — see also: https://snyk.io/test/npm/hugo-bin

**Comment by XhmikosR** [comment]
Either way, there's nothing we can do at this point. This needs to be fixed upstream.

**Comment by h-enk** [comment]
> Either way, there's nothing we can do at this point. 

Knowing the last commit to bin-wrapper was [Nov 7, 2018](https://github.com/kevva/bin-wrapper/commits/master), would make a case looking for a replacement.

**Comment by XhmikosR** [comment]
Again, nothing I can do. You are welcome to propose a solid PR, but I'm not going to just replace the package myself.

**Comment by h-enk** [comment]
OK, clear then

**Comment by XhmikosR** [comment]
This doesn't happen any more https://github.com/fenneclab/hugo-bin/runs/3513009958#step:4:23

**Comment by doly-doly** [comment]
6 high severity vulnerabilities
when i use:
  npm audit fix --force 
it showes
69 vulnerabilities (13 low, 19 moderate, 34 high, 3 critical)
and I getinside unlimited loop 
so what to do !

**Comment by Kalimelakuu** [comment]
'npm set audit false' would solve your issues

**Comment by XhmikosR** [comment]
I just released v0.100.0 which is using my @xhmikosr/bin-wrapper fork. All current security vulnerabilities should be gone and hopefully no bugs.

If anyone spots any bugs feel free to make a PR and CC me. I don't have the bandwidth to actively maintain those forks, I just wanted the vulnerabilities gone.

**Comment by chadlwilson** [comment]
Seems to be working for me and has cleared the GitHub security advisories. Thanks for the effort @XhmikosR !

**Comment by pantharshit007** [comment]
not able to understand where this problme starts form doing `npm audit --force` is just a vicious cycle of loop 

`

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...


added 1486 packages in 2m

250 packages are looking for funding
  run `npm fund` for details

Initialized a git repository.

Installing template dependencies using npm...

added 69 packages, and changed 1 package in 19s

254 packages are looking for funding
  run `npm fund` for details
Removing template package using npm...


removed 1 package, and audited 1555 packages in 9s

254 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (2 moderate, 6 high)

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

`

one way to escape is changing the react-scripts from dependencies --> devDependencies

`"dependencies": {
"@testing-library/jest-dom": "^5.17.0",
"@testing-library/react": "^13.4.0",
"@testing-library/user-event": "^13.5.0",
"nth-check": "^2.0.1",
"postcss": "^8.4.31",
"react": "^18.2.0",
"react-scripts": "^5.0.1",
"react-dom": "^18.2.0",
"web-vitals": "^2.1.4"

},`

`"devDependencies": {
"react-scripts": "^5.0.1"
},`
