### ISSUE TITLE
Commonjs version?

### ISSUE THREAD

**Issue by nabilfreeman** [fenneclab/hugo-bin#116]
Hey there, I couldn't get this working on AWS Lambda Node 14 despite it supposedly supporting ES modules. I had to manually download hugo myself and make a small wrapper around child_process to execute it.

It would be useful if this had a Commonjs version.

If you like the idea, let me know if you would like a hand making this happen (never done before but I'm sure I can figure it out!)

**Comment by XhmikosR** [comment]
You could stick to an older version; 0.77.4 is the last non-ESM version.

**Comment by nabilfreeman** [comment]
Got it thanks! I see this is a recent change from December, so hopefully the ecosystem catches up soon 🤞

**Comment by XhmikosR** [comment]
TBH most people use the package as a CLI module :)

Also, the needed Node.js versions are `^12.20.0 || ^14.13.1 || >=16.0.0` which are old enough.

I decided to go with way because everything is faster and cleaner, but happy to accept a clean/slim PR that supports both.
