### ISSUE TITLE
Transitive dependency vulnerability

### ISSUE THREAD

**Issue by kingthorin** [fenneclab/hugo-bin#117]
Heya, any chance you could be talked into addressing this?

```
 Dependabot cannot update semver-regex to a non-vulnerable version

The latest possible version that can be installed is 2.0.0 because of the following conflicting dependency:

hugo-bin@0.81.0 requires semver-regex@^2.0.0 via a transitive dependency on find-versions@3.2.0
```

**Comment by XhmikosR** [comment]
Nothing more I can do, this is coming from upstream packages. I have made upstream PRs, but they appear unmaintained, see https://github.com/kevva/bin-wrapper/issues/79#issuecomment-1011967842

**Comment by XhmikosR** [comment]
BTW you can see here using my forks: https://github.com/fenneclab/hugo-bin/compare/dev-packages

So, if someone goes ahead and publishes scoped packages with the fixes, we could switch to them here too.

**Comment by kingthorin** [comment]
@XhmikosR thanks for the update, Sorry to hear you're caught in the middle 😢 I guess this is one of the downsides that comes with node use.

**Comment by XhmikosR** [comment]
See https://github.com/fenneclab/hugo-bin/issues/114#issuecomment-1469496820
