### ISSUE TITLE
Windows OS - 'rm' is not recognized as an internal or external command.

### ISSUE THREAD

**Issue by jormenes** [fenneclab/hugo-bin#12]
Hi, this seems to be an issue for non Unix systems.

### Info
Version: hugo-bin@0.6.0
OS: Windows 7 / cmd.exe
Arch: x64

### Error:
```bash
npm install
> hugo-bin@0.6.0 postinstall C:\dev\...\node_modules\hugo-bin
> rm -rf vendor && node lib/install
**'rm' is not recognized as an internal or external command, operable program or batch file**

Exit status 1
...
```

### What is expected?
Post Install script should not throw an error.

### What is actually happening?
`rm` command for deleting files is a command available in unix systems only, windows uses a different command (del). Maybe the `rimraf` module could be used as workaround. <https://github.com/isaacs/rimraf>

Thanks.

**Comment by satoshun00** [comment]
Fixed on `0.6.1`. Thank you for reporting!
