### ISSUE TITLE
Security vulnerability hugo-bin v0.98.0

### ISSUE THREAD

**Issue by markdumay** [fenneclab/hugo-bin#126]
The current version `0.98.0` of hugo-bin contains a high severity vulnerability. Below are the results from `npm audit`. I'm not sure if a fix for your dependencies is available already. You might want to consider setting up Dependabot alerts in the security section of your GitHub repository.

```
# npm audit report

cacheable-request  <=10.2.6
Severity: high
cacheable-request depends on http-cache-semantics, which is vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-8x6c-cv3v-vp6g
Depends on vulnerable versions of http-cache-semantics
No fix available
node_modules/cacheable-request
  got  <=12.4.1
  Depends on vulnerable versions of cacheable-request
  node_modules/got
    download  >=4.0.0
    Depends on vulnerable versions of got
    node_modules/download
      bin-wrapper  >=0.4.0
      Depends on vulnerable versions of bin-version-check
      Depends on vulnerable versions of download
      node_modules/bin-wrapper
        hugo-bin  *
        Depends on vulnerable versions of bin-wrapper
        node_modules/hugo-bin
```

**Comment by coliff** [comment]
I think this has been discussed already in https://github.com/fenneclab/hugo-bin/issues/114#issuecomment-865667585

**Comment by markdumay** [comment]
Thanks, I overlooked that issue. Too bad it won't be addressed.

**Comment by XhmikosR** [comment]
See https://github.com/fenneclab/hugo-bin/issues/114#issuecomment-1469496820
