### ISSUE TITLE
Did recent changes prevent log files from being generated

### ISSUE THREAD

**Issue by ZhangChengLin** [fenneclab/hugo-bin#139]
Nice to see the recent reduction in dependencies, thanks for the effort.
Recently, I found that the hugo command line did not generate a log file. I wonder if it has something to do with the recent reduction of dependencies? ?
Not sure what the reason is, because it has been updated frequently recently.

**Comment by ZhangChengLin** [comment]
> 

This option is generally used, and a real-time log file is generated in the root directory of the project, because sometimes the content of my console is lost after switching the size. So almost all commands use Hugo's log parameter, and there was no problem not long ago. Not sure what went wrong. No log files have been debugged, nor any related error prompts.


https://gohugo.io/commands/hugo/
https://gohugo.io/commands/hugo_server/#options-inherited-from-parent-commands

>       --log                        enable Logging
>      --logFile string             log File path (if set, logging enabled automatically)

**Comment by XhmikosR** [comment]
That's unrelated to hugo-bin, you should report it upstream to hugo.
