### ISSUE TITLE
Wrong binary installed for linux/arm64

### ISSUE THREAD

**Issue by bubenkoff** [fenneclab/hugo-bin#141]
```
501.3 npm ERR! code 1
501.3 npm ERR! path /go/src/quriobot/api/kb/node_modules/hugo-bin
501.4 npm ERR! command failed
501.4 npm ERR! command sh -c node lib/install.js
501.4 npm ERR! Hugo binary installation failed!
501.4 npm ERR! file:///node_modules/hugo-bin/lib/install.js:39
501.4 npm ERR!       throw new Error(error);
501.4 npm ERR!             ^
501.4 npm ERR!
501.4 npm ERR! Error: Error: Command failed with ENOENT: node_modules/hugo-bin/vendor/hugo version
501.4 npm ERR! spawn node_modules/hugo-bin/vendor/hugo ENOENT
501.4 npm ERR!     at file:///node_modules/hugo-bin/lib/install.js:39:13
501.4 npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
501.4 npm ERR!
501.4 npm ERR! Node.js v18.17.0
501.5
```

please suggest a fix

**Comment by XhmikosR** [comment]
Works fine on CI, and for plenty of people out there. Also, without more info, there's nothing that can be done.

**Comment by bubenkoff** [comment]
This happens with the latest version available on npm, during the docker builds for linux/arm64 platform
please let me know what more info you need.
thanks

**Comment by bubenkoff** [comment]
@XhmikosR looking at CI setup: https://github.com/fenneclab/hugo-bin/blob/main/.github/workflows/ci.yml
there's no linux/arm64 platform installation check, right?

**Comment by XhmikosR** [comment]
There's no support for arm64 without a hosted runner on GitHub Actions CI.

1. Which version last worked for you? The relevant code hasn't changed here for quite some time: https://github.com/fenneclab/hugo-bin/blob/main/lib/index.js
2. Which upstream binary works for you from upstream?

**Comment by bubenkoff** [comment]
@XhmikosR Yes there isn't arm64 support for the runners, so why would you claim that it's all 'checked' by CI and works for other people without providing any proof and closing the issue?
 The last one that worked fine for me was 0.79.0. But didn't upgrade for quite some time.

**Comment by XhmikosR** [comment]
So, the important thing to you is whether my statement was right because I don't want to pay in order to test the platform you might be using?

That's not how open source works.

**Comment by bubenkoff** [comment]
Thank you for teaching me how open source works.
I am not at all saying someone should pay for the fix nor the test.
I am asking for the attention to the details of the reported issue, instead
of blindly closing them.
The issue persists, please let me know how can I help with it
Thank you for the great project.
