### ISSUE TITLE
Update Hugo to the latest release

### ISSUE THREAD

**Issue by XhmikosR** [fenneclab/hugo-bin#29]
Hi, @satoshun00.

Can you update to the latest release?

Also, what are your plans for this? Do you plan to update to new versions in the foreseeable future? I ask because I plan to use this in Bootstrap and I don't like reinventing the wheel.

Thanks!

**Comment by satoshun00** [comment]
Thank you for reminding me!
I'll publish hugo-bin 0.17.0 tomorrow.
