### ISSUE TITLE
Versioning and updates

### ISSUE THREAD

**Issue by dmgawel** [fenneclab/hugo-bin#33]
Although hugo-bin is very useful and helps me build my website easily it's versioning is confusing. I'd like to propose mirroring Hugo versions, so hugo-bin v0.29 would ship Hugo v0.29. Old versions 
 (< 0.17) might be left intact. 

I think this would ease reasoning about hugo-bin and would allow development of auto-publishing mechanism.

**Comment by satoshun00** [comment]
Thank you for suggestion!
But it's not make sense to me, because "mirroring Hugo versions" prevents reasonable versioning of `hugo-bin` itself.

When hugo-bin v0.30.2 ships gohugoio/hugo v0.30.2, and if hugo-bin needs to upgrade some dependencies, hugo-bin cannot increment patch version 😭
