### ISSUE TITLE
Vulnerabilities and deprecations in the sub dependencies

### ISSUE THREAD

**Issue by tlaak** [fenneclab/hugo-bin#45]
Hugo-bin is using **bin-wrapper** 3.0.2 that is dependent on vulnerable version of **download**. It's also dependent on **gulp-util** 3.0.8 which is deprecated. There is an [open issue](https://github.com/kevva/bin-wrapper/issues/55) in the bin-wrapper repository.

**Comment by satoshun00** [comment]
Thank you for reporting, I'm waiting for a while for a bin-wrapper new release.

**Comment by naeluh** [comment]
I would also be into this fix thanks!

**Comment by XhmikosR** [comment]
Does anybody know an alternative to the `download` package?

**Comment by satoshun00** [comment]
Suppose I replace `bin-wrapper`:

- `os-filter-obj`: filter platform and arch
- `node-fetch`: download an asset
- `crypto`: check the checksum from the asset (https://github.com/fenneclab/hugo-bin/issues/36)
- `decompress`: extract zip

**Comment by satoshun00** [comment]
ref: https://github.com/kevva/bin-wrapper/pull/60

**Comment by XhmikosR** [comment]
Unfortunately, it doesn't seem bin-wrapper is maintained at all.

**Comment by tlaak** [comment]
The updates have been merged to bin-wrapper master, but it hasn't been published to npm yet.

**Comment by XhmikosR** [comment]
Yup, I'm following that myself :) I already have a branch for the node.js 4.x removal which will need to happen with the update.

**Comment by jhabdas** [comment]
https://github.com/kevva/bin-wrapper/releases/tag/v4.0.0
