### ISSUE TITLE
Code signature complaining 

### ISSUE THREAD

**Issue by bcomnes** [fenneclab/hugo-bin#46]
Trying to hunt down why the little snitch is trying to block outgoing connections from Hugo installed with this module

![screen shot 2018-03-29 at 9 50 20 am](https://user-images.githubusercontent.com/166301/38101979-b42e892c-3336-11e8-8097-f109f47a9f78.png)

Are these Hugo bin signed?

**Comment by XhmikosR** [comment]
The binaries should be whatever the upstream ones are. So, I don't see how this is related to this wrapper.

Just my 2¢.

**Comment by bcomnes** [comment]
I'll look around some more
