### ISSUE TITLE
New Hugo version

### ISSUE THREAD

**Issue by XhmikosR** [fenneclab/hugo-bin#60]
@satoshun00: I suggest that you don't close this issue and people can just comment when a new version is out.

**Comment by XhmikosR** [comment]
BTW I don't know which of the two binaries you should include by default.

@bep: any suggestions?

**Comment by jhabdas** [comment]
> BTW I don't know which of the two binaries you should include by default.

Probably don't include the extended by default, given it's _extended_?

**Comment by bep** [comment]
@XhmikosR it's a good question ...  This is all still fairly new, but people seem to really like the extended version (which currently adds SCSS/SASS support). The name "extended" is a little random, but we have to produce two sets of binaries for several reasons:

* one being that I have not set up the build-chain to provide it for all the exotic platforms.
* and (at least the MacOS and Linux version) requires a compatible glibc++ version, which may be a problem in some minimalistic Docker setups...

I know Netlify is switching to use the extended by default, if that helps.

**Comment by XhmikosR** [comment]
@bep: thanks for the reply!

I guess the "wise" thing would be to stay with the normal version for now maybe.

**Comment by XhmikosR** [comment]
@satoshun00: how about this issue?

**Comment by satoshun00** [comment]
@XhmikosR 
I will do it in order. (0.44 -> 0.45.1 -> 0.46 -> 0.47.1 -> 0.48 -> 0.49.2)

**Comment by XhmikosR** [comment]
I don't see why that's needed, since these are already old versions...

**Comment by satoshun00** [comment]
@XhmikosR 
I think skipping version is not user friendly to a package that depends on old version of Hugo.
hugo-bin has no ability to choose the specific Hugo version.

**Comment by XhmikosR** [comment]
But these are not released in `hugo-bin`. You are going back in time ;)

**Comment by satoshun00** [comment]
Just in case you didn't know, I plan to release each versions:

0.44: hugo-bin=0.32.0
0.45.1: hugo-bin=0.33.0
0.46: hugo-bin=0.34.0
0.47.1: hugo-bin=0.35.0
...

I know this is a bit confusing to users, but I think is better than having no choice.

**Comment by XhmikosR** [comment]
Closing this since it's fixed. Thanks!
