### ISSUE TITLE
New Hugo version

### ISSUE THREAD

**Issue by XhmikosR** [fenneclab/hugo-bin#84]
I'm gonna try to keep this open so that we don't create a new issue for each release @satoshun00

**Comment by XhmikosR** [comment]
https://gohugo.io/news/0.52-relnotes/

**Comment by peaceiris** [comment]
https://gohugo.io/news/0.55.5-relnotes/

**Comment by XhmikosR** [comment]
https://github.com/fenneclab/hugo-bin/releases/tag/v0.43.5
